[project]
name = "master-thesis-3d-vla"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    # VGGT deps
    "torch>=2.7",
    "torchvision>=0.22",
    "numpy==1.26.1",
    "Pillow",
    "huggingface_hub",
    "einops",
    "safetensors",
    # notebook
    "ipykernel",
    "matplotlib",
    "manim>=0.18.1",
]

[tool.uv]
python-preference = "only-managed"
